### PR TITLE
Added Swift Example section

### PR DESCRIPTION
**Pull request by unnamedd**
https://github.com/Zewo/GraphQLExamples

GraphQLExamples is an example of GraphQL implemented in Swift

### CODE REVIEW

**Comment by stubailo** [comment]
Can we clarify that this is specifically for Swift on the server? Since it's primarily used as a client-side language for iOS development right now, I think it would be confusing without that extra information.

**Comment by unnamedd** [comment]
Oh yes, of course! It's done!

**Comment by stubailo** [comment]
Grammar correction:

> GraphQL examples to your backend in Swift using

Should probably be:

> Examples of how to build your GraphQL backend in Swift using

**Comment by unnamedd** [comment]
Hey @stubailo thank you for your suggestion, it's already done! 
I really appreciate that! ;)

**Comment by stubailo** [comment]
Hey I think this is a bit confusing because the ToC doesn't match the order of the document now. Can you just add your example for now, and not reorder anything?

**Pull request closed without merging**
