### PR TITLE
Added `async-graphql`

### PR DESCRIPTION
**Pull request by jayeshmann**
https://github.com/async-graphql/async-graphql

[Comparison with `juniper`](https://github.com/async-graphql/async-graphql/blob/master/feature-comparison.md)

### CODE REVIEW

**Comment by dbanty** [comment]
I also have a PR open for this in #642 😄

**Comment by jayeshmann** [comment]
@dbanty Apologies, I didn't see that. Also, add it alphabetically.

**Comment by dbanty** [comment]
Oh is alphabetical a requirement? I wasn’t sure what to do because the existing entries are not sorted in any way I could tell. 

Yours has an extra link with more detail anyway so I’ll just close mine 😅. Doesn’t seem like merges are happening soon here anyway.

**Comment by jayeshmann** [comment]
@dbanty Thanks for your kind consideration!

**Review by chentsulin — APPROVED** [review]

**Pull request merged**
