### PR TITLE
Add vim-graphql to the Tools list

### PR DESCRIPTION
**Pull request by jparise**
https://github.com/jparise/vim-graphql

vim-graphql is a Vim plugin that provides GraphQL file detection and
syntax highlighting.

"Tools" appears to be the best place for this currently, but it might
make sense to introduce an "Editors" list at some point.

### CODE REVIEW

**Comment by jparise** [comment]
Build failure is for an unrelated Vimeo link (https://vimeo.com/144817545) which returns HTTP 403 (to the Travis environment; works fine in the browser).

**Comment by stubailo** [comment]
Yeah it's really unfortunate that builds always fail on unrelated PRs.

**Comment by stubailo** [comment]
Odd, it passes from my computer, but not on Travis.

**Comment by jparise** [comment]
I suspect Vimeo denies robot-like requests from Travis/curl/AWS.

**Comment by stubailo** [comment]
Gonna try to fix it here: https://github.com/chentsulin/awesome-graphql/pull/123

**Comment by stubailo** [comment]
Can you rebase on `master`? Looks like my change fixed the build.

**Comment by jparise** [comment]
@stubailo All set!

**Comment by jparise** [comment]
All good, @stubailo?

**Comment by stubailo** [comment]
Thanks!

**Pull request merged**
