### PR TITLE
adding application example which uses contextable.js for GraphQL root…

### PR DESCRIPTION
**Pull request by xpepermint**
**[URL to the resource here.]**
https://github.com/xpepermint/graphql-example

**[Explain what this resource is all about and why it should be included here.]**
This example application shows a new way of writing GraphQL resolvers by using [contextable.js](https://github.com/xpepermint/contextablejs) framework. The example shows how to write nested types, how to validate user input data and respond with user-friendly validation errors, how to create GraphQL HTTP server and how to structure your app as a long-term sustainable project.

**[Value]**
Contextable.js has a reach API which significantly simplifies server-side and client-side data validation and manipulation. I started using it in all my GraphQL applications (in production). It helps me write less code and my code is clean and easy to read. I strongly believe that it will help others as well.

### CODE REVIEW

**Comment by stubailo** [comment]
I think this should link directly to the GraphQL example, rather than to contextable itself.

**Comment by xpepermint** [comment]
@stubailo Hum... I think I provided only the link to the example. :confused:?

**Comment by stubailo** [comment]
Oh, sorry - I got confused looking at the diff. Perhaps we can shorten the description (make it more practical and less hyperbolic) and remove the link directly to contextable?

**Comment by xpepermint** [comment]
I think that the link to contextable is useful but you can remove it if you insist ;). What do you propose for the description? Are we talking about the description in my commit or here?

**Comment by stubailo** [comment]
> as GraphQL rootValue on steroids (nested schema, input validation, context-aware models, database implementation, project structure and more)

I guess this doesn't really tell me what it is - what's a context-aware model or a database implementation in the context of this library?

**Comment by xpepermint** [comment]
OK, then just `Application example using contextable.js`?

**Comment by stubailo** [comment]
Sure, thanks

**Comment by xpepermint** [comment]
:thumbsup:

**Pull request merged**
