### PR TITLE
Add graphql-spqr and a Java (+Spring MVC) example

### LINKED ISSUE #315: Add graphql-spqr
Please add [GraphQL-SPQR](https://github.com/leangen/graphql-spqr) to the Java section. It's been an active project for years.

GraphQL SPQR is a simple-to-use library for rapid development of GraphQL APIs in Java, in the code-first approach. It integrates easily into any Java based stack, with examples using Spring Boot and Spring MVC provided.

It is featured on Awesome graphql-java and has been the subject of multiple conference talks:

* [Amsterdam Codemotion 2017](https://www.youtube.com/watch?v=1zIHHi2MaQE)
* [Devoxx Belgium 2018](https://www.youtube.com/watch?v=iyt7PwkUWQA)

I made a [PR](https://github.com/chentsulin/awesome-graphql/pull/207) that's been rotting for almost a year now, so I opened an issue to try getting some attention.

### PR DESCRIPTION
**Pull request by kaqqao**
Adding [GraphQL SPQR](https://github.com/leangen/GraphQL-SPQR) to the Java libraries section.

Closes #315

### CODE REVIEW

**Comment by kaqqao** [comment]
Soon this PR will celebrate its 1 birthday 🎂

**Comment by TreTuna** [comment]
Dupes

**Comment by kaqqao** [comment]
I have no clue what happened here... The PR is closed because it's a duplicate (of what?), but the related issue #315 is still open?

**Comment by TreTuna** [comment]
Hmm... I'm sorry, I think this one was a mistake on my part. When I was looking at it last night something got confused and it was listing this as already in the repo. Happy to reopen this one!

**Comment by TreTuna** [comment]
Also, this has some issues from CI that I believe should be solved by bringing this branch up-to-date with the current master.

**Comment by kaqqao** [comment]
No worries, I'll fix it up in a minute. Thanks for giving it attention!

**Pull request merged**
