### PR TITLE
Remove unmaintained/abandoned golang graphql implementations

### PR DESCRIPTION
**Pull request by pyros2097**

### CODE REVIEW

**Comment by chentsulin** [comment]
@tmc Would you suggest people use https://github.com/chris-ramon/graphql at this moment?
If so, we can just remove those and keep active projects for developers.

**Comment by pyros2097** [comment]
Yep... https://github.com/chris-ramon/graphql is being actively developed by some of us and we are going to use it in production.

**Comment by tmc** [comment]
I actively use my stuff for personal projects and have been revving on oct2015 spec adherence.

**Comment by chentsulin** [comment]
@pyros2097 
Could you only remove cryptix/go-graphql and keep tmc/graphql in this repo? We'd like to keep projects diversity in the community at this moment.

**Comment by pyros2097** [comment]
Oops.. Didn't think anyone was using yours @tmc. I'll fix it. And also fixed the link for graphql-go to graphql.

**Pull request merged**
