### PR TITLE
Add GraphQL Armor

### PR DESCRIPTION
**Pull request by glimow**
**https://github.com/Escape-Technologies/graphql-armor**

**An easy-to-use, production-ready middleware to instantly protect js-based GraphQL servers.**

### CODE REVIEW

**Comment by setchy** [comment]
@GiladShoham - thanks for the contribution.  can you please add to the bottom of the `Others` section 🙏

**Comment by GiladShoham** [comment]
@setchy I think you were tagging the wrong person :)

**Comment by setchy** [comment]
> @setchy I think you were tagging the wrong person :)

ooops 🙈

**Comment by setchy** [comment]
@glimow  - thanks for the contribution. can you please add to the bottom of the `Others` section 🙏

**Comment by setchy** [comment]
Added to main

**Pull request closed without merging**
