### PR TITLE
Add graphql-ts in typescript library

### PR DESCRIPTION
**Pull request by nicolasgere**
https://github.com/nicolasgere/graphql-ts

What people hate in typescript it's we use some package create for javascript not for typescript, so we have to maintain multiple 'modele' for each package, a graphql model with specific type, same thing with mongoose etc... my package avoid that with the power of reflection and typescript typing

```js
import {field} from 'graphql-ts'

class root{
  @field
  hello():string{
    return "world"
  }
}
```

it's cleaner than

```js

import {
  graphql,
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLString
} from 'graphql';

var schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      hello: {
        type: GraphQLString,
        resolve() {
          return 'world';
        }
      }
    }
  })
});

```

### CODE REVIEW

**Comment by stubailo** [comment]
Can you make the description more specific? What helps typescript developers in your library?

**Comment by nicolasgere** [comment]
is it better? i updated my precedent post

**Comment by stubailo** [comment]
Yeah I mean in your PR, make it more descriptive than "GraphQL server for typescript" since any JavaScript thing works with typescript.

**Comment by nicolasgere** [comment]
ho sorry,i missunderstood, right now it's good? i dont found a better way to describe the package

**Comment by nicolasgere** [comment]
Sorry, i do not understand, this will be merge or not?

**Comment by chentsulin** [comment]
@stubailo @schickling I am not a typescript user, so it's hard to give any suggestion. Can you give some suggestion or are we ready to merge this one?

**Comment by schickling** [comment]
@nicolasgere I think what @stubailo is saying is that in order to build a GraphQL server in Typescript (by that I don't mean a GraphQL server-side implementation of the spec) you can also use the "normal" Javascript implementation with the [corresponding type definitions](https://www.npmjs.com/package/@types/graphql).

So maybe you can make it a bit clearer in your descriptions what's the benefit of your implementation over that?

**Comment by nicolasgere** [comment]
yes but the normal js implementation, you have to use <any> everywhere or to create a lot of interface for your type, maintain a model in typescript and one in graphql-js. My package juste avoid that, and as i did in the exemple, the code is more clear and short.

**Comment by TreTuna** [comment]
Project is no longer maintained.

**Pull request closed without merging**
