### PR TITLE
graph-spec proposal for JavaScript

### PR DESCRIPTION
**Pull request by rricard**
One of my own libraries, found it useful to test graphql schemas fast. Makes GraphQL + TDD less repetitive and more fun in my opinion!

### CODE REVIEW

**Comment by stubailo** [comment]
Hi @rricard, is this still being maintained?

**Comment by rricard** [comment]
@stubailo We still use it in our project, may need some improvements, but after using it, I may see one thing or two to add/improve. At this point I'm not sure however we should merge that here!

**Comment by stubailo** [comment]
@rricard if you're actually using it then we should put it in! I think most libraries here are not very popular, just was asking because there weren't commits in a while.

**Comment by rricard** [comment]
@stubailo let me refine it and I'll make an another proposal: no rush!

**Pull request closed without merging**
