### PR TITLE
Added SwitchQL to tools list

### PR DESCRIPTION
**Pull request by laueian**
https://github.com/SwitchQL/SwitchQL

SwitchQL automates the transcription of database schemas into GraphQL schemas, resolvers, queries, and mutations. Due to the security concerns when connecting to databases, the electron desktop application allows for use of the tool within a user's network or VPC.

We see this tool as helping new graphql users form a better understanding of graphql, but we also see potential for developers and companies to integrate this tool into a CI/CD pipeline or assist in a migration to graphql.

If you have any questions please feel free to reach out - laueian@gmail.com. Thanks!

### CODE REVIEW

**Comment by TreTuna** [comment]
This sounds like a very interesting tool that I'd love to get on the list, however before we merge this in, can you flesh out the Readme for people that are browsing through these. Currently, one would see it on this list with the quick description, go to the project page, and have no idea what's going on or what to do.

**Comment by laueian** [comment]
I will report back as soon as we have finished the readme :)

**Comment by TreTuna** [comment]
I look forward to it! Sounds like a great tool for helping people show GraphQL to others and try to get it adopted more widely!

**Comment by laueian** [comment]
We've update the readme and have released version 1.0! Let me know what you think 
! [image](https://user-images.githubusercontent.com/22291673/58376223-a5db4a00-7f1a-11e9-8abb-b2cae0d04237.png)

**Comment by laueian** [comment]
@TreTuna Any chance you'll be able to take a look soon? We're really excited about our first release and we already plan to release plugins for mssql and mysql :)

**Comment by TreTuna** [comment]
Awesome and congrats! I'm sorry I hadn't had time to get back to this until now.

**Pull request merged**
