### PR TITLE
Graph-quill proposal for JS/Relay

### PR DESCRIPTION
**Pull request by rricard**
One of my own libs that I use on my personal projects. Really helps on the relay-side of the schema creation since it's always the most difficult part in my opinion.

### CODE REVIEW

**Comment by stubailo** [comment]
@rricard is this still being maintained?

**Comment by rricard** [comment]
@stubailo some people seems to be using it but not me. As of now I would redirect people to use the graphql type definition syntax instead of that. So let's close it, thanks for asking me, I forgot about it!

**Comment by stubailo** [comment]
Cool!

**Comment by nodkz** [comment]
@rricard see on `graphql-compose` https://github.com/nodkz/graphql-compose-examples/blob/master/examples/northwind/graphqlSchema.js
Server: https://graphql-compose.herokuapp.com/
Relay client on the northwind schema: https://nodkz.github.io/relay-northwind/
 
Maybe you'd like it. 😉

**Comment by rricard** [comment]
@nodkz I have already been taken by the Apollo GraphQL Tools! 😉  But I'll give that a try for a relay-based project!

**Pull request closed without merging**
